"""AI-powered resume tailoring service — Steps 4-5 of the pipeline (prompt
build + the single OpenAI request).

Tailoring policy: employer names, employment dates, education, and
certifications are IDENTITY FACTS spliced verbatim from MasterCvData -
never sent to or generated by the AI. Everything else - the professional
summary, the full Skills list, and every job's experience bullets - is
generated by the AI to best fit the target job description, not limited to
what the candidate's real CV already shows for that job/skillset (see
app/prompts/resume_tailor_prompt.py for the exact instructions).

Two prompt/output paths:
- Structured (preferred, when MasterCvData.is_structured): builds a compact
  prompt from pre-parsed CV/JD data and asks for TailoredDynamicContent
  (summary + skills + per-job title/bullets). Job title/company/dates are
  spliced from MasterCvData afterward, overriding anything the AI wrote for
  them. Any bullet shortfall is padded from other JD-driven jobs' bullets,
  then deterministic JD-derived filler as a last resort - never from the
  candidate's real original bullets, since bullets are meant to be fully
  JD-driven now.
- Fallback (raw CV text): used when structuring wasn't confident (PDF
  upload, or an unusual DOCX layout) - asks the model for the full
  TailoredResumeContent schema directly from the whole CV text.

Uses AsyncOpenAI rather than the sync client so the multi-second network
round trip never blocks FastAPI's event loop - with a sync client, one
in-flight tailoring request would stall every other request the server is
handling (including unrelated /health checks), which matters at scale.
"""
import logging
import time

import httpx
from openai import APIConnectionError, APITimeoutError, AsyncOpenAI

from app.core.config import settings
from app.core.constants import EXPERIENCE_BULLET_COUNT, FIXED_LANGUAGES_SECTION
from app.models.schemas import (
    AtsMatchInfo,
    ExperienceEntry,
    JdAnalysis,
    MasterCvData,
    ResumeMatch,
    TailoredDynamicContent,
    TailoredResumeContent,
)
from app.prompts.resume_tailor_prompt import (
    RESUME_TAILOR_SYSTEM_PROMPT,
    build_dynamic_refinement_message,
    build_refinement_message,
    build_structured_user_message,
    build_user_message,
    get_dynamic_system_prompt,
)
from app.services.ats_scorer import compute_ats_match
from app.services.cv_structurer import clip_job_company, clip_job_title
from app.services.resume_validator import bullets_missing_metrics, normalize_ai_skills
from app.services.text_sanitize import strip_broken_characters
from app.utils.timing import PerfReport


logger = logging.getLogger("resume_tailor.ai")


class AiTailoringError(Exception):
    """Raised when the AI tailoring request fails."""


# Module-level singleton, created lazily on first use and reused for every
# request. Instantiating AsyncOpenAI per-request (the previous behavior)
# meant paying a fresh TLS handshake + connection-pool setup on every single
# tailor request instead of reusing a keep-alive connection to OpenAI - a
# real, avoidable chunk of the "everything except the model's own think time"
# latency budget. Safe to share across concurrent requests: AsyncOpenAI's
# underlying httpx client is async-safe or an asyncio event loop.
_client: AsyncOpenAI | None = None


def _get_client() -> AsyncOpenAI:
    global _client
    if _client is None:
        # timeout: per-ATTEMPT ceiling (read/write/pool vs. a shorter
        # connect timeout - see settings docstrings). max_retries: the
        # SDK's own built-in retry/backoff for timeouts, connection errors,
        # and 429/5xx (see openai._base_client - exponential backoff with
        # jitter, bounded, never endless) - deliberately NOT reimplemented
        # by hand here; _parse_completion below only adds a distinct,
        # narrower fallback for a param-support issue, not for
        # timeouts/connection errors, which the SDK already handles.
        _client = AsyncOpenAI(
            api_key=settings.openai_api_key,
            timeout=httpx.Timeout(
                settings.openai_request_timeout_seconds,
                connect=settings.openai_connect_timeout_seconds,
            ),
            max_retries=settings.openai_max_retries,
        )
    return _client


def reset_openai_client() -> None:
    """Drop the cached AsyncOpenAI client so the next call rebuilds it
    from current settings (model/timeout/retries). Used on lifespan
    startup after a full process restart picks up a new .env."""
    global _client
    _client = None


# Model name prefixes for reasoning-family models that accept
# reasoning_effort (see settings.openai_reasoning_effort's docstring for why
# this is the dominant latency lever for this app). Non-reasoning models
# (gpt-4o*, gpt-4.1*, gpt-3.5*, etc.) reject an unknown reasoning_effort
# param outright, so this MUST stay opt-in by model name, never global.
_REASONING_MODEL_PREFIXES = ("o1", "o3", "o4", "gpt-5")


def _is_reasoning_model(model: str) -> bool:
    return model.lower().startswith(_REASONING_MODEL_PREFIXES)


def _timeout_error_message(exc: Exception) -> str:
    """Build a self-diagnosing timeout error message that prints the
    ACTUAL currently-active config (model/timeout/retries) rather than a
    generic "try again" - this is what a request timeout almost always
    traces back to in this app (in order of likelihood):
    1. OPENAI_MODEL is a reasoning model (gpt-5*, o1/o3/o4*) - these can
       spend 8-230+s of hidden reasoning per attempt, blowing even a
       generous per-attempt timeout.
    2. .env was edited but the server process was never actually
       restarted - `uvicorn --reload`'s file-watcher only reacts to *.py
       changes by default, NOT .env, so an edited OPENAI_MODEL/timeout
       value silently never takes effect until a full process restart.
    3. A genuine network/connectivity problem reaching api.openai.com
       (firewall, proxy, DNS, no internet) - every attempt/retry fails the
       same way regardless of model.
    Logged at warning level AND returned to the caller (surfaced in the
    frontend's error message) so this is diagnosable without needing
    server console access.
    """
    is_reasoning = _is_reasoning_model(settings.openai_model)
    attempts = settings.openai_max_retries + 1
    message = (
        f"OpenAI request timed out after {attempts} attempt(s) "
        f"(model={settings.openai_model!r}, timeout={settings.openai_request_timeout_seconds:.0f}s/attempt): {exc}. "
    )
    if is_reasoning:
        message += (
            f"{settings.openai_model!r} is a reasoning model — ensure "
            "OPENAI_REASONING_EFFORT=minimal, OPENAI_REQUEST_TIMEOUT_SECONDS is "
            f"at least 120, and OPENAI_MAX_OUTPUT_TOKENS is high enough "
            f"(currently {settings.openai_max_output_tokens}) for reasoning + "
            "visible output. FULLY RESTART the server after editing backend/.env "
            "(--reload does not pick up .env changes)."
        )
    else:
        message += (
            "If you just edited backend/.env, fully restart the server process (stop and re-run "
            "uvicorn) - .env changes are not picked up by --reload. If you did restart and this "
            "persists, verify network access to api.openai.com from this machine and that "
            "OPENAI_API_KEY is valid."
        )
    logger.warning(message)
    return message


async def _parse_completion(client: AsyncOpenAI, messages: list[dict], response_format: type):
    extra_kwargs: dict = {}
    is_reasoning = _is_reasoning_model(settings.openai_model)
    if settings.openai_reasoning_effort and is_reasoning:
        extra_kwargs["reasoning_effort"] = settings.openai_reasoning_effort
    if settings.openai_max_output_tokens:
        # Applied for ALL models. On gpt-5* this budget covers hidden
        # reasoning tokens AND the visible JSON — too low truncates or
        # returns empty structured output; too high lets runaway reasoning
        # burn the timeout. See settings.openai_max_output_tokens.
        extra_kwargs["max_completion_tokens"] = settings.openai_max_output_tokens

    try:
        completion = await client.chat.completions.parse(
            model=settings.openai_model,
            messages=messages,
            response_format=response_format,
            **extra_kwargs,
        )
    except (APITimeoutError, APIConnectionError) as exc:
        # The SDK already retried this internally settings.openai_max_retries
        # times, with exponential backoff, before giving up (see
        # _get_client's docstring) - by the time we see this, it's a real
        # exhaustion, not a one-off blip. Do NOT fall through to the
        # "retry without extra_kwargs" path below: that's for a completely
        # different failure mode (a param the model rejects), and retrying
        # a request that just exhausted its timeout budget would only add
        # latency, not fix anything.
        raise AiTailoringError(_timeout_error_message(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        if extra_kwargs:
            # This specific model/snapshot may not actually accept
            # reasoning_effort/max_completion_tokens even though it matched
            # the reasoning-prefix check above - retry once without them
            # rather than failing the whole request over a speed
            # optimization. (Not reached for timeout/connection errors -
            # see the except clause above.)
            try:
                completion = await client.chat.completions.parse(
                    model=settings.openai_model,
                    messages=messages,
                    response_format=response_format,
                )
            except (APITimeoutError, APIConnectionError) as exc2:
                raise AiTailoringError(_timeout_error_message(exc2)) from exc2
            except Exception as exc2:  # noqa: BLE001
                raise AiTailoringError(f"OpenAI request failed: {exc2}") from exc2
        else:
            raise AiTailoringError(f"OpenAI request failed: {exc}") from exc

    parsed = completion.choices[0].message.parsed
    if parsed is None:
        raise AiTailoringError("The AI response could not be parsed into a resume.")
    return parsed


# Last-resort, no-AI filler for the rare case the model returns fewer than
# EXPERIENCE_BULLET_COUNT bullets for a job even after being asked for
# exactly that many. Deliberately built from the JD's own required/
# preferred skills, never from that job's real CV duties - bullets are
# fully JD-driven under the current tailoring policy, so padding must stay
# JD-driven too rather than falling back to the candidate's real original
# work (see app/prompts/resume_tailor_prompt.py).
_GENERIC_BULLET_TEMPLATES = (
    "Delivered {skill}-focused improvements, lifting measurable output by {n}%.",
    "Applied {skill} to streamline delivery, cutting turnaround time by {n}%.",
    "Partnered cross-functionally to advance {skill} adoption, improving reliability by {n}%.",
    "Led initiatives leveraging {skill}, boosting throughput and quality by {n}%.",
)
_GENERIC_BULLET_NUMBERS = (15, 20, 25, 30, 35, 40)


def _generic_jd_bullets(jd_analysis: JdAnalysis, count: int) -> list[str]:
    pool = list(jd_analysis.required_skills) + list(jd_analysis.preferred_skills) or ["cross-functional delivery"]
    bullets = []
    for i in range(count):
        skill = pool[i % len(pool)]
        template = _GENERIC_BULLET_TEMPLATES[i % len(_GENERIC_BULLET_TEMPLATES)]
        number = _GENERIC_BULLET_NUMBERS[i % len(_GENERIC_BULLET_NUMBERS)]
        bullets.append(template.format(skill=skill, n=number))
    return bullets


def _assemble_full_resume(
    master_cv: MasterCvData,
    dynamic: TailoredDynamicContent,
    jd_analysis: JdAnalysis,
) -> TailoredResumeContent:
    """Splice AI-generated summary/skills/experience with the master CV's
    real identity facts (contact/education/company/dates/title).

    Job title always comes from the master CV (cv_entry.title), never the
    AI's suggestion - see .cursor/rules/resume-tailoring-prompt-rules.mdc's
    "use the master CV's job title for every experience entry" rule. An
    empty parsed title stays empty rather than substituting a JD-aligned
    invention.

    Every job's bullets are padded/trimmed to exactly
    EXPERIENCE_BULLET_COUNT - every selectable template has exactly this
    many fixed bullet slots per job (see app/services/template_renderer.py).
    Bullets are fully JD-driven now (not restricted to that job's real
    duties), so any shortfall is padded from other jobs' JD-driven bullets
    first, then deterministic JD-derived filler - never from the
    candidate's real original bullets."""
    experience: list[ExperienceEntry] = []
    for i, cv_entry in enumerate(master_cv.experience):
        if i < len(dynamic.experience):
            dyn_entry = dynamic.experience[i]
            title = cv_entry.title
            bullets = list(dict.fromkeys(dyn_entry.bullets or []))
        else:
            title = cv_entry.title
            bullets = []

        if len(bullets) < EXPERIENCE_BULLET_COUNT:
            pool: list[str] = []
            for j, other in enumerate(dynamic.experience):
                if j == i:
                    continue
                pool.extend(b for b in other.bullets if b not in bullets and b not in pool)
            bullets = bullets + pool[: EXPERIENCE_BULLET_COUNT - len(bullets)]
        if len(bullets) < EXPERIENCE_BULLET_COUNT:
            bullets = bullets + _generic_jd_bullets(jd_analysis, EXPERIENCE_BULLET_COUNT - len(bullets))
        bullets = bullets[:EXPERIENCE_BULLET_COUNT]

        clipped_title = clip_job_title(title)
        experience.append(
            ExperienceEntry(
                title=clipped_title,
                company=clip_job_company(cv_entry.company, clipped_title),
                dates=strip_broken_characters(cv_entry.dates),
                bullets=bullets,
            )
        )

    return TailoredResumeContent(
        contact=master_cv.contact,
        summary=dynamic.summary,
        skills=normalize_ai_skills(dynamic.skills, master_cv),
        experience=experience,
        education=master_cv.education,
        certifications=master_cv.certifications_raw,
        languages=list(FIXED_LANGUAGES_SECTION),
    )


async def tailor_resume(
    master_cv: MasterCvData,
    jd_analysis: JdAnalysis,
    resume_match: ResumeMatch,
    job_description: str,
    bullets_per_job: list[int] | None = None,
    perf: PerfReport | None = None,
    mode: str | None = None,
) -> tuple[TailoredResumeContent, AtsMatchInfo]:
    """Generate a tailored resume. Uses the compact structured prompt +
    dynamic-only output schema when master_cv.is_structured; otherwise
    falls back to the original raw-CV-text prompt + full output schema.

    perf, when provided, records "Prompt Build", "OpenAI", and "Validation"
    (ATS re-scoring after each pass) stage timings for the caller's
    end-of-request performance report.

    mode selects "accurate" (default), "aggressive", or "aggressive_match"
    tailoring intensity (see app/prompts/resume_tailor_prompt.py) - defaults
    to settings.tailoring_mode when not passed explicitly. All three modes
    generate bullets/skills/summary fully around the JD; "aggressive" and
    "aggressive_match" just push harder for JD alignment (more assertive
    rewriting, bigger refinement budget) to reach the ATS target, with
    "aggressive_match" being the strongest of the two. Identity facts
    (real company/dates/title) are never AI-authored regardless of mode. A
    deterministic, non-AI top-up pass for "aggressive_match" lives in
    app/services/resume_validator.close_ats_gaps, called by the route after
    this function returns - not here, since it needs the caller's
    already-computed ResumeMatch and mutates the resume in place.

    Exactly ONE OpenAI call by default for all modes
    (settings.ats_max_refine_attempts / aggressive_ats_max_refine_attempts /
    aggressive_match_ats_max_refine_attempts all default to 0) - required for
    the <5s tailor target. No sequential follow-up request happens unless a
    refine budget is explicitly raised above 0. When refine > 0, a follow-up
    call is made only when the previous pass's score is still below target
    OR any experience bullet still has no quantifiable metric (see
    resume_validator.bullets_missing_metrics). Each refinement pass is a
    full extra OpenAI round trip that depends on the previous pass's output
    (so it can never be parallelized away); follow-up passes feed back the
    specific missing keywords/unquantified bullets, and the best result
    across all passes is kept. ATS gaps after the single default call are
    still closed for free by close_ats_gaps (Skills top-up, no AI).

    With the default openai_model (gpt-4o-mini, non-reasoning), the single
    call typically completes in ~1-4s, which is the happy path for the <5s
    target. settings.tailoring_time_budget_seconds (checked before each
    refinement attempt) and openai_request_timeout_seconds (a per-call
    timeout) are the safety nets that keep this bounded even if the API is
    unusually slow, rather than the expected case.
    """
    if not settings.openai_api_key:
        raise AiTailoringError(
            "OPENAI_API_KEY is not configured on the server. Set it in backend/.env."
        )

    mode = mode or settings.tailoring_mode
    if mode == "aggressive_match":
        max_refine_attempts = settings.aggressive_match_ats_max_refine_attempts
    elif mode == "aggressive":
        max_refine_attempts = settings.aggressive_ats_max_refine_attempts
    else:
        max_refine_attempts = settings.ats_max_refine_attempts

    own_perf = perf or PerfReport(label="tailor_resume")
    client = _get_client()
    structured = master_cv.is_structured
    call_started_at = time.perf_counter()
    logger.info(
        "tailor_resume path=%s jobs=%d mode=%s max_out=%s",
        "structured" if structured else "fallback_full",
        len(master_cv.experience),
        mode,
        settings.openai_max_output_tokens,
    )

    with own_perf.stage("Prompt Build"):
        if structured:
            system_prompt = get_dynamic_system_prompt(mode)
            user_message = build_structured_user_message(
                master_cv, jd_analysis, resume_match, job_description, bullets_per_job, mode=mode
            )
        else:
            system_prompt = RESUME_TAILOR_SYSTEM_PROMPT
            user_message = build_user_message(master_cv.raw_text, job_description, bullets_per_job)

    response_format = TailoredDynamicContent if structured else TailoredResumeContent
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
    ]

    def _to_full_resume(result: TailoredDynamicContent | TailoredResumeContent) -> TailoredResumeContent:
        if structured:
            return _assemble_full_resume(master_cv, result, jd_analysis)
        # Fallback: the AI already produced a full JD-driven skills list -
        # just normalize casing/dedupe, never overwrite its content.
        full = result
        full.skills = normalize_ai_skills(full.skills, master_cv)
        return full

    with own_perf.stage("OpenAI"):
        result = await _parse_completion(client, messages, response_format)
    with own_perf.stage("Validation"):
        full_resume = _to_full_resume(result)
        ats_match = compute_ats_match(full_resume, job_description, jd_analysis)

    best_full, best_match = full_resume, ats_match
    best_weak_bullets = bullets_missing_metrics(best_full)
    attempts = 0
    while (
        (
            (best_match.score < settings.ats_score_target and best_match.missing_keywords)
            # Every bullet must carry a quantifiable metric (see
            # resume_validator.bullets_missing_metrics) - even once the
            # keyword score already clears target, spend a refinement pass
            # on this if any bullet still has no number, since it's a hard
            # quality requirement independent of ATS keyword coverage.
            or best_weak_bullets
        )
        and attempts < max_refine_attempts
        # Soft overall deadline (see settings.tailoring_time_budget_seconds) -
        # never start a NEW refinement call once we're already close to the
        # app's total tailoring-time target; return the best result found
        # so far instead. Checked before starting the call, not after, so
        # we never pay for a call we already know would blow the budget.
        and (time.perf_counter() - call_started_at) < settings.tailoring_time_budget_seconds
    ):
        refinement_message = (
            build_dynamic_refinement_message(ats_match.missing_keywords, mode=mode, weak_bullets=best_weak_bullets)
            if structured
            else build_refinement_message(ats_match.missing_keywords, weak_bullets=best_weak_bullets)
        )
        messages.append({"role": "assistant", "content": result.model_dump_json()})
        messages.append({"role": "user", "content": refinement_message})

        with own_perf.stage("OpenAI"):
            result = await _parse_completion(client, messages, response_format)
        with own_perf.stage("Validation"):
            full_resume = _to_full_resume(result)
            ats_match = compute_ats_match(full_resume, job_description, jd_analysis)
            weak_bullets = bullets_missing_metrics(full_resume)
        attempts += 1

        # Keep this pass's result if it improved keyword coverage, or held
        # keyword coverage steady while quantifying more bullets - never
        # regress on one axis to chase the other.
        if ats_match.score > best_match.score or (
            ats_match.score >= best_match.score and len(weak_bullets) < len(best_weak_bullets)
        ):
            best_full, best_match, best_weak_bullets = full_resume, ats_match, weak_bullets

    return best_full, best_match
